// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: twitter/tweet/rpc/tweet.proto

package rpc

import (
	resources "github.com/K-Kizuku/Somniosus_back/proto.pb/twitter/tweet/resources"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTweetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content *resources.CreateTweet `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *CreateTweetRequest) Reset() {
	*x = CreateTweetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twitter_tweet_rpc_tweet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTweetRequest) ProtoMessage() {}

func (x *CreateTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_twitter_tweet_rpc_tweet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTweetRequest.ProtoReflect.Descriptor instead.
func (*CreateTweetRequest) Descriptor() ([]byte, []int) {
	return file_twitter_tweet_rpc_tweet_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTweetRequest) GetContent() *resources.CreateTweet {
	if x != nil {
		return x.Content
	}
	return nil
}

type CreateTweetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tweet *resources.Tweet `protobuf:"bytes,1,opt,name=tweet,proto3" json:"tweet,omitempty"`
}

func (x *CreateTweetResponse) Reset() {
	*x = CreateTweetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twitter_tweet_rpc_tweet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTweetResponse) ProtoMessage() {}

func (x *CreateTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twitter_tweet_rpc_tweet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTweetResponse.ProtoReflect.Descriptor instead.
func (*CreateTweetResponse) Descriptor() ([]byte, []int) {
	return file_twitter_tweet_rpc_tweet_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTweetResponse) GetTweet() *resources.Tweet {
	if x != nil {
		return x.Tweet
	}
	return nil
}

type GetTweetTLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *GetTweetTLRequest) Reset() {
	*x = GetTweetTLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twitter_tweet_rpc_tweet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTweetTLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetTLRequest) ProtoMessage() {}

func (x *GetTweetTLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_twitter_tweet_rpc_tweet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetTLRequest.ProtoReflect.Descriptor instead.
func (*GetTweetTLRequest) Descriptor() ([]byte, []int) {
	return file_twitter_tweet_rpc_tweet_proto_rawDescGZIP(), []int{2}
}

func (x *GetTweetTLRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetTweetTLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tl []*resources.Tweet `protobuf:"bytes,1,rep,name=tl,proto3" json:"tl,omitempty"`
}

func (x *GetTweetTLResponse) Reset() {
	*x = GetTweetTLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twitter_tweet_rpc_tweet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTweetTLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetTLResponse) ProtoMessage() {}

func (x *GetTweetTLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twitter_tweet_rpc_tweet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetTLResponse.ProtoReflect.Descriptor instead.
func (*GetTweetTLResponse) Descriptor() ([]byte, []int) {
	return file_twitter_tweet_rpc_tweet_proto_rawDescGZIP(), []int{3}
}

func (x *GetTweetTLResponse) GetTl() []*resources.Tweet {
	if x != nil {
		return x.Tl
	}
	return nil
}

type DeleteTweetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TweetId string `protobuf:"bytes,1,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
}

func (x *DeleteTweetRequest) Reset() {
	*x = DeleteTweetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twitter_tweet_rpc_tweet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTweetRequest) ProtoMessage() {}

func (x *DeleteTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_twitter_tweet_rpc_tweet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTweetRequest.ProtoReflect.Descriptor instead.
func (*DeleteTweetRequest) Descriptor() ([]byte, []int) {
	return file_twitter_tweet_rpc_tweet_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTweetRequest) GetTweetId() string {
	if x != nil {
		return x.TweetId
	}
	return ""
}

var File_twitter_tweet_rpc_tweet_proto protoreflect.FileDescriptor

var file_twitter_tweet_rpc_tweet_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x11, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x72,
	0x70, 0x63, 0x1a, 0x23, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x74, 0x77, 0x65, 0x65,
	0x74, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x74, 0x77, 0x65, 0x65,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x77, 0x65, 0x65, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x4b, 0x0a,
	0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x74, 0x77, 0x65, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72, 0x2e, 0x74, 0x77,
	0x65, 0x65, 0x74, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x54, 0x77,
	0x65, 0x65, 0x74, 0x52, 0x05, 0x74, 0x77, 0x65, 0x65, 0x74, 0x22, 0x32, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x54, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x44,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x54, 0x4c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x02, 0x74, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74,
	0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x54, 0x77, 0x65, 0x65, 0x74,
	0x52, 0x02, 0x74, 0x6c, 0x22, 0x2f, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x77,
	0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x77,
	0x65, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x77,
	0x65, 0x65, 0x74, 0x49, 0x64, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x4b, 0x2d, 0x4b, 0x69, 0x7a, 0x75, 0x6b, 0x75, 0x2f, 0x53, 0x6f, 0x6d,
	0x6e, 0x69, 0x6f, 0x73, 0x75, 0x73, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x70, 0x62, 0x2f, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x74, 0x77, 0x65,
	0x65, 0x74, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_twitter_tweet_rpc_tweet_proto_rawDescOnce sync.Once
	file_twitter_tweet_rpc_tweet_proto_rawDescData = file_twitter_tweet_rpc_tweet_proto_rawDesc
)

func file_twitter_tweet_rpc_tweet_proto_rawDescGZIP() []byte {
	file_twitter_tweet_rpc_tweet_proto_rawDescOnce.Do(func() {
		file_twitter_tweet_rpc_tweet_proto_rawDescData = protoimpl.X.CompressGZIP(file_twitter_tweet_rpc_tweet_proto_rawDescData)
	})
	return file_twitter_tweet_rpc_tweet_proto_rawDescData
}

var file_twitter_tweet_rpc_tweet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_twitter_tweet_rpc_tweet_proto_goTypes = []interface{}{
	(*CreateTweetRequest)(nil),    // 0: twitter.tweet.rpc.CreateTweetRequest
	(*CreateTweetResponse)(nil),   // 1: twitter.tweet.rpc.CreateTweetResponse
	(*GetTweetTLRequest)(nil),     // 2: twitter.tweet.rpc.GetTweetTLRequest
	(*GetTweetTLResponse)(nil),    // 3: twitter.tweet.rpc.GetTweetTLResponse
	(*DeleteTweetRequest)(nil),    // 4: twitter.tweet.rpc.DeleteTweetRequest
	(*resources.CreateTweet)(nil), // 5: twitter.tweet.resources.CreateTweet
	(*resources.Tweet)(nil),       // 6: twitter.tweet.resources.Tweet
}
var file_twitter_tweet_rpc_tweet_proto_depIdxs = []int32{
	5, // 0: twitter.tweet.rpc.CreateTweetRequest.content:type_name -> twitter.tweet.resources.CreateTweet
	6, // 1: twitter.tweet.rpc.CreateTweetResponse.tweet:type_name -> twitter.tweet.resources.Tweet
	6, // 2: twitter.tweet.rpc.GetTweetTLResponse.tl:type_name -> twitter.tweet.resources.Tweet
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_twitter_tweet_rpc_tweet_proto_init() }
func file_twitter_tweet_rpc_tweet_proto_init() {
	if File_twitter_tweet_rpc_tweet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_twitter_tweet_rpc_tweet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTweetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_twitter_tweet_rpc_tweet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTweetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_twitter_tweet_rpc_tweet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTweetTLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_twitter_tweet_rpc_tweet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTweetTLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_twitter_tweet_rpc_tweet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTweetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_twitter_tweet_rpc_tweet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_twitter_tweet_rpc_tweet_proto_goTypes,
		DependencyIndexes: file_twitter_tweet_rpc_tweet_proto_depIdxs,
		MessageInfos:      file_twitter_tweet_rpc_tweet_proto_msgTypes,
	}.Build()
	File_twitter_tweet_rpc_tweet_proto = out.File
	file_twitter_tweet_rpc_tweet_proto_rawDesc = nil
	file_twitter_tweet_rpc_tweet_proto_goTypes = nil
	file_twitter_tweet_rpc_tweet_proto_depIdxs = nil
}
